# Generated by Django 5.2.6 on 2025-09-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="movie_genre",
            field=models.CharField(
                choices=[
                    ("Comedy", "Comedy"),
                    ("Romance", "Romance"),
                    ("Action", "Action"),
                    ("Drama", "Drama"),
                    ("Horror", "Horror"),
                    ("Sci-Fi", "Sci-Fi"),
                ],
                max_length=50,
            ),
        ),
    ]
